env: standard
service: frontend
runtime: nodejs18

env_variables:
  VUE_APP_API_KEY: AIzaSyA59aDjYSI8VA4CuCwirvWgtuahaDC5zZk
  VUE_APP_AUTH_DOMAIN: codeway-task-33a0d.firebaseapp.com
  VUE_APP_PROJECT_ID: codeway-task-33a0d
  VUE_APP_STORAGE_BUCKET: codeway-task-33a0d.appspot.com
  VUE_APP_MESSAGING_SENDER_ID: 771845127594
  VUE_APP_APP_ID: 1:771845127594:web:12e67d561cddede3aeffd3
  VUE_APP_MEASUREMENT_ID: G-59PS8TNRK1

automatic_scaling:
  target_cpu_utilization: 0.65

handlers:
  - url: /css
    static_dir: dist/css

  - url: /js
    static_dir: dist/js

  - url: /img
    static_dir: dist/img

  - url: /favicon.ico
    static_files: dist/favicon.ico
    upload: dist/favicon.ico

  - url: /manifest.json
    static_files: dist/manifest.json
    upload: dist/manifest.json

  - url: /(.*\.(json|ico|txt))$
    static_files: dist/\1
    upload: dist/.*\.(json|ico|txt)$

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
